### PR TITLE
Restructure routes

### PR DESCRIPTION
**Pull request by ArihantRJain**
Restructuring routes.js into Controllers and Routers.

### CODE REVIEW

**Review by ukanirudh — COMMENTED** [review]
Can we make the changes where, in listing APIs instead of doing 'temp.data = null;' , do 'temp.data = [];'

**Comment by ArihantRJain** [comment]
@ukanirudh , Akshay will be making those changes after this PR is merged.

**Review by ukanirudh — COMMENTED** [review]
One thing we can consider doing is, 
'ResponseFormat' function can take parameters, 'status', 'message' and 'data' and create a new object where-ever is required by passing the parameters.
Var temp and overriding it at multiple places causes the same object to be manipulated everywhere and can cause inconsistency . In that way you can also save 3 lines of code repeated at multiple places and instead replace with single line of code

**Comment by ArihantRJain** [comment]
temp is a local variable to each route, so it is not getting overridden anywhere. 
We can try the parameter approach to initialize ResponseFormat.

**Review by ukanirudh — APPROVED** [review]

**Comment by ArihantRJain** [comment]
We are facing an issue with the Mailer module during sign up. We will need to fix it before merging.

**Comment by ArihantRJain** [comment]
@ameeakshay, There was an issue with the Mailer Module due to the restructuring. We weren't passing the app object to any of the modules. We are now accessing the app object through the req object.

**Review by ameeakshay — APPROVED** [review]
All the routes are working fine.
Will be merging these cahnges.

**Pull request merged**
